POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "name": "My Product",
  "price": 100
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcxNDUwMDksInN1YiI6Ijc4OTVkYmYwLWYxMDItNGI1Yi04YjRjLTZkZjdjNjE4NjEzMSJ9.3g4F2LOglmGzq6Bvt7hb6GgyPDklIKAS5oGSu_i8Bvw

####

GET http://localhost:8000/products/4b46eec0-7502-4a93-b413-9d0bc8486439 HTTP/1.1

####

PUT http://localhost:8000/products/4b46eec0-7502-4a93-b413-9d0bc8486439 HTTP/1.1
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

#####

DELETE  http://localhost:8000/products/4b46eec0-7502-4a93-b413-9d0bc8486439 HTTP/1.1
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

